import { createClient } from 'next-sanity'
import { config } from 'dotenv'

config({ path: '.env.local' })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!,
  apiVersion: '2026-08-13',
  token: process.env.SANITY_API_WRITE_TOKEN!,
  useCdn: false,
})

function blockText(text: string) {
  return [
    {
      _type: 'block',
      _key: crypto.randomUUID().slice(0, 8),
      style: 'normal',
      markDefs: [],
      children: [
        {
          _type: 'span',
          _key: crypto.randomUUID().slice(0, 8),
          text,
          marks: [],
        },
      ],
    },
  ]
}

async function main() {
  if (!process.env.SANITY_API_WRITE_TOKEN) {
    console.error(
      'Missing SANITY_API_WRITE_TOKEN.\n' +
      'Create one at sanity.io/manage → your project → API → Tokens with Editor permission.\n' +
      'Add it to .env.local as SANITY_API_WRITE_TOKEN=sk-...'
    )
    process.exit(1)
  }

  console.log('Creating AEO/GEO service page...')

  const servicePageDoc = {
    _id: 'servicePage-aeo-geo',
    _type: 'servicePage',
    title: 'AEO / GEO',
    slug: { _type: 'slug', current: 'answer-engine-optimization-and-ai-search-optimization-services' },
    section: 'services',
    summary: 'AEO & GEO services for the next generation of search',
    pageBuilder: [
      // 1. Hero Section
      {
        _type: 'heroSection',
        _key: 'hero-1',
        badgeText: 'Certified Google Partner',
        headline: 'AEO & GEO Services For The Next Generation Of Search',
        subheadline: 'Search is no longer limited to traditional search engines. Customers now discover answers through AI systems, conversational interfaces, and generative search platforms.',
        ctaText: 'Get Your Search Leak Map',
        ctaLink: '/contact-search-performance-marketing-agency',
      },
      // 2. Text + Image — AEO Services intro (no image, heading-left / text-right split)
      {
        _type: 'textImageSection',
        _key: 'text-image-1',
        heading: 'AEO Services by High Horse: Get Found in AI Answers',
        bodyText: blockText('High Horse helps businesses optimise their digital presence through Answer Engine Optimization (AEO) and Generative Engine Optimization (GEO). We ensure your brand appears in AI-generated responses, knowledge panels, and conversational search results so you stay visible, relevant, and ahead where modern search decisions happen.'),
      },
      // 3. Card Grid — Understanding AEO & GEO
      {
        _type: 'cardGridSection',
        _key: 'card-grid-1',
        heading: 'Understanding Answer Engine & Generative Engine Optimization',
        subtext: 'Traditional search engines show a list of links. Modern search platforms increasingly deliver direct answers generated by AI systems.',
        cards: [
          {
            _key: 'card-aeo-1',
            title: 'Answer Engine Optimization (AEO)',
            description: 'AEO focuses on structuring your content so search engines can extract clear answers and present them directly to users. This improves visibility in:',
            bullets: ['Featured snippets', 'Voice search responses', 'Knowledge panels', 'Instant answer boxes'],
          },
          {
            _key: 'card-geo-1',
            title: 'Generative Engine Optimization (GEO)',
            description: 'GEO focuses on ensuring AI models recognise and reference your brand when generating responses. This helps your brand appear in:',
            bullets: ['AI-generated search summaries', 'Conversational AI platforms', 'Research assistants and generative search tools', 'AI-powered discovery platforms'],
          },
        ],
      },
      // 4. Text + Image — Why AEO & GEO Are Important
      {
        _type: 'textImageSection',
        _key: 'text-image-2',
        heading: 'Why AEO & GEO Are Important for Businesses',
        bodyText: blockText('Consumer search behaviour is rapidly changing. Instead of clicking through multiple websites, users now ask questions directly to AI-powered systems and expect immediate answers. If your brand is not optimised for these systems:'),
        bullets: [
          'Your competitors may appear in the answers instead of you',
          'Your content may never be surfaced to users',
          'Your brand visibility may decline as AI-driven search grows',
        ],
        closingText: 'Businesses that adopt AEO and GEO strategies early gain a significant advantage in AI-driven discovery and brand authority.',
        imagePosition: 'right',
      },
      // 5. Text + Image — How AEO & GEO Help
      {
        _type: 'textImageSection',
        _key: 'text-image-3',
        heading: 'How AEO & GEO Help Businesses Grow',
        bodyText: blockText('Optimising for AI search platforms creates several strategic advantages. AEO and GEO help businesses:'),
        bullets: [
          'Increase brand visibility across AI-powered search platforms',
          'Appear in featured answers and knowledge panels',
          'Build stronger credibility and authority signals',
          'Capture high-intent informational search traffic',
          'Improve brand recognition during early research stages',
        ],
        closingText: 'Instead of competing only for rankings, your brand becomes part of the answers customers trust.',
        imagePosition: 'left',
      },
      // 6. Card Grid — Our AEO & GEO Services
      {
        _type: 'cardGridSection',
        _key: 'card-grid-2',
        heading: 'Our AEO & GEO Services',
        subtext: 'Our AEO & GEO services are designed to position your brand where modern users search and discover — inside AI-driven answers and conversational results.',
        cards: [
          {
            _key: 'svc-aeo',
            title: 'Answer Engine Optimization (AEO)',
            description: 'Structure and optimize your website content so search engines extract clear answers and feature them in snippets, knowledge panels, and instant results.',
          },
          {
            _key: 'svc-geo',
            title: 'Generative Engine Optimization (GEO)',
            description: 'Position your brand to appear in AI-generated answers by optimizing content, authority signals, and entity recognition across generative search systems.',
          },
          {
            _key: 'svc-ai-search',
            title: 'AI Search Optimization',
            description: 'Optimize your digital presence for AI-powered discovery platforms by aligning content with conversational queries, semantic relevance, and machine-readable formats.',
          },
          {
            _key: 'svc-snippet',
            title: 'Featured Snippet Optimization',
            description: 'Design content structures that increase your chances of appearing in position-zero results where search engines pull direct answers.',
          },
          {
            _key: 'svc-kg',
            title: 'Knowledge Graph & Entity Optimization',
            description: 'Strengthen your brand\'s entity signals so search engines clearly understand your business, expertise, and relationships within the knowledge graph.',
          },
          {
            _key: 'svc-semantic',
            title: 'AI Content Structuring & Semantic SEO',
            description: 'Create semantically structured content that helps search engines and AI systems easily interpret, organize, and deliver your information as trusted answers.',
          },
        ],
      },
      // 7. Card Grid — Our Approach
      {
        _type: 'cardGridSection',
        _key: 'card-grid-3',
        heading: 'Our Approach to AI Search Optimization',
        subtext: 'High Horse helps brands prepare their digital presence for AI-driven search ecosystems through a structured strategy.',
        cards: [
          {
            _key: 'approach-1',
            title: 'Conversational Search Optimization',
            description: 'Identifying natural language questions users ask AI systems.',
          },
          {
            _key: 'approach-2',
            title: 'Content Structuring for AI Platforms',
            description: 'Creating content frameworks designed for easy extraction by search engines and AI models.',
          },
          {
            _key: 'approach-3',
            title: 'Entity-Based SEO Optimization',
            description: 'Strengthening how search engines recognise your brand as an authoritative entity.',
          },
          {
            _key: 'approach-4',
            title: 'Structured Data Implementation',
            description: 'Using schema markup to improve content interpretation by AI systems.',
          },
          {
            _key: 'approach-5',
            title: 'Topical Authority Development',
            description: 'Building comprehensive content ecosystems that demonstrate subject expertise.',
          },
          {
            _key: 'approach-6',
            title: 'AI Search Visibility Monitoring',
            description: 'Tracking how your brand appears across AI-generated responses and search platforms.',
          },
        ],
      },
      // 8. Text + Image — Why Choose High Horse
      {
        _type: 'textImageSection',
        _key: 'text-image-4',
        heading: 'Why Choose High Horse',
        bodyText: blockText('Most agencies still optimise only for traditional rankings. High Horse combines advanced SEO strategies with AI search optimisation frameworks designed for modern discovery systems. Our advantage includes:'),
        bullets: [
          'Deep expertise in AI-driven search evolution',
          'Structured content frameworks designed for AI extraction',
          'Integration of SEO, AEO, and GEO strategies',
          'Performance-focused digital marketing approach',
          'Continuous monitoring of AI search visibility',
        ],
        closingText: 'We focus on building search systems designed for long-term visibility.',
        imagePosition: 'right',
      },
      // 9. CTA Section
      {
        _type: 'ctaSection',
        _key: 'cta-1',
        heading: 'Work With an Agency Built for the Future of Search',
        bodyText: blockText('Search is evolving into an ecosystem powered by intelligent systems, real-time data, and AI-driven decision making. Traditional SEO approaches are no longer enough to maintain visibility in this environment. As an agentic SEO agency, High Horse builds adaptive search strategies designed to operate within modern search ecosystems. Our approach combines human expertise with AI-powered analysis to continuously optimise content, structure, and visibility across both traditional and AI-driven search platforms. By aligning SEO, AEO, and GEO frameworks, we help businesses stay visible wherever customers discover information — whether through search engines, conversational AI, or generative search systems. The result is a search strategy that is not only optimized for today\'s algorithms, but designed to evolve with the future of digital discovery.'),
        ctaText: 'Lets Get on a call',
        ctaLink: '/contact-search-performance-marketing-agency',
      },
    ],
  }

  await client.createOrReplace(servicePageDoc)
  console.log('✓ Service page created:', servicePageDoc._id)

  // Create 5 FAQ documents
  const faqs = [
    {
      _id: 'faq-aeo-geo-1',
      question: 'How do we know if our business needs AEO or GEO services?',
      order: 1,
    },
    {
      _id: 'faq-aeo-geo-2',
      question: 'How long does it take to see results from AEO and GEO optimization?',
      order: 2,
    },
    {
      _id: 'faq-aeo-geo-3',
      question: 'Do we still need traditional SEO along with AEO and GEO?',
      order: 3,
    },
    {
      _id: 'faq-aeo-geo-4',
      question: 'Which industries benefit the most from AEO and GEO services?',
      order: 4,
    },
    {
      _id: 'faq-aeo-geo-5',
      question: 'What makes High Horse different from other AEO/GEO agencies?',
      order: 5,
    },
  ]

  for (const faq of faqs) {
    await client.createOrReplace({
      _type: 'faq',
      _id: faq._id,
      question: faq.question,
      answer: blockText('TODO: content team to write answer'),
      category: 'seo',
      relatedPage: {
        _type: 'reference',
        _ref: servicePageDoc._id,
      },
      order: faq.order,
    })
    console.log('✓ FAQ created:', faq.question)
  }

  // Update the service page to reference all FAQs
  await client.patch(servicePageDoc._id).set({
    relatedFaqs: faqs.map((f) => ({
      _type: 'reference',
      _ref: f._id,
      _key: f._id,
    })),
  }).commit()
  console.log('✓ Linked FAQs to service page')

  console.log('\nDone! Visit /answer-engine-optimization-and-ai-search-optimization-services')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
